# Generated by Django 3.1.7 on 2021-04-13 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_contactform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='Contact',
        ),
    ]
