# Generated by Django 3.1.7 on 2021-04-13 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_auto_20210413_2305'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
