# Generated by Django 3.1.7 on 2021-04-13 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('mob', models.CharField(max_length=15)),
                ('mess', models.TextField()),
                ('time', models.DateTimeField(default=datetime.datetime(2021, 4, 13, 23, 28, 20, 140187))),
            ],
        ),
    ]
